In [1]:
import warnings
warnings.filterwarnings('ignore')
import pandas as pd
import numpy as np

In [7]:
categories = [
    'Automobile',
    'Beverages',
    'Clothing',
    'Entertainment',
    'Electronics',
    'Jewellery',
    'Food',
    'Makeup',
    'Non-profit',
    'Shoes'
]

quadrants = [
    'HF-HE',
    'HF-LE',
    'LF-HE',
    'LF-LE',
]
totsum = 0
for quad in quadrants:
    sum = 0
    for category in categories:
        path = f'D://Study//Project//Major project//{category}//{category}_{quad}_captions.xlsx'
        df = pd.read_excel(path)
        sum  = sum + df.shape[0]
    
    print(quad, ":", sum)
    totsum = totsum + sum
print("Total sum:", totsum)

HF-HE : 3461
HF-LE : 9447
LF-HE : 14955
LF-LE : 881
Total sum: 28744

In [ ]:
fisrt_file = pd.read_excel('')

In [7]:
categories = [
    'jewellery',
    'shoes'
]

for category in categories:
    first_file_path = f'D://Study//Project//Major project//24 hours//{category}//1H_comment_count_{category}.xlsx'
    first_file = pd.read_excel(first_file_path)
    for hours in range(2, 25):
        path = f"D://Study//Project//Major project//24 hours//{category}//{hours}H_comment_count_{category}.xlsx"
        df = pd.read_excel(path)
        first_file[f'{hours}H_Comment_Counts'] = df[f'{hours}H_Comment_Counts']
    first_file.to_excel(f'comment_count_24_hours_{category}.xlsx', index = False)

In [6]:
first_file.head()

,Influencers,1H_Comment_Counts,2H_Comment_Counts,3H_Comment_Counts,4H_Comment_Counts,5H_Comment_Counts,6H_Comment_Counts,7H_Comment_Counts,8H_Comment_Counts,9H_Comment_Counts,...,15H_Comment_Counts,16H_Comment_Counts,17H_Comment_Counts,18H_Comment_Counts,19H_Comment_Counts,20H_Comment_Counts,21H_Comment_Counts,22H_Comment_Counts,23H_Comment_Counts,24H_Comment_Counts
0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,007underconstruction,1.0,3.0,3.0,5.0,5.0,5.0,5.0,5.0,5.0,...,5.0,5.0,5.0,5.0,6.0,6.0,6.0,6.0,6.0,7.0
2,03nataliagaitan,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,100social,2.5,2.5,2.5,2.5,2.5,2.5,2.5,2.5,2.5,...,2.5,2.5,2.5,2.5,2.5,2.5,2.5,2.5,2.5,2.5
4,111sidora,9.0,13.0,13.0,13.0,13.0,13.0,14.0,14.0,14.0,...,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0,15.0